# Site settings
title: Gerben Jacobs
header-img: img/flickr-theonewithout-fencers.jpg
email: info@gerbenjacobs.nl
description: "A personal blog"
baseurl: ""
url: "http://blog.gerbenjacobs.nl"
twitter_username: gerbenjacobs
github_username:  gerbenjacobs
facebook_username:  gerbenjacobs

# Build settings
markdown: kramdown
highlighter: pygments
permalink: none
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
