# Site settings
title: Gerben Jacobs
header-img: img/home-bg.jpg
description: The personal blog of Gerben Jacobs; software engineer, father, husband.
url: https://blog.gerbenjacobs.nl
twitter_username: gerbenjacobs
github_username:  gerbenjacobs
linkedin_username: gerbenjacobs

# Build settings
markdown: kramdown
permalink: none
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
plugins: ["jekyll-paginate"]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true