# Site settings
title: Gerben Jacobs
header-img: img/flickr-theonewithout-fencers.jpg
description: A personal blog
url: https://blog.gerbenjacobs.nl
twitter_username: gerbenjacobs
github_username:  gerbenjacobs
linkedin_username: gerbenjacobs

# Build settings
markdown: kramdown
#highlighter: rouge
permalink: none
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
plugins: ["jekyll-paginate"]