baseURL: 'https://blog.gerbenjacobs.nl'
languageCode: 'en-us'
title: Gerben Jacobs
#description: The personal blog of Gerben Jacobs; software engineer, father, husband.
theme: bootspoon
paginate: 6
enableRobotsTXT: true
enableEmoji: true
enableInlineShortcodes: true
permalinks:
  posts: '/:slug'
disqusShortname: 'gerbenjacobs'
googleAnalytics: G-KKSLTF3X24
taxonomies:
  tags: tags