baseURL: 'https://blog.gerbenjacobs.nl'
languageCode: 'en-us'
title: Gerben Jacobs
theme: bootspoon
paginate: 6
enableRobotsTXT: true
enableEmoji: true
enableInlineShortcodes: true
permalinks:
  posts: '/:slug'
disqusShortname: 'gerbenjacobs'
googleAnalytics: 'G-KKSLTF3X24'
taxonomies:
  tags: tags