baseURL: 'https://blog.gerbenjacobs.nl'
languageCode: 'nl-nl'
title: Gerben Jacobs
theme: bootspoon
pagination:
  pagerSize: 6
enableRobotsTXT: true
enableEmoji: true
enableInlineShortcodes: true
enableGitInfo: true
permalinks:
  posts: '/:slug'
disqusShortname: 'gerbenjacobs'
googleAnalytics: 'G-KKSLTF3X24'
taxonomies:
  tags: tags